### ISSUE TITLE
Problema ao executar o programa

### ISSUE THREAD

**Issue by lvlofenix** [leticia-alves-ime/teste-Target#1]
Olá, boa tarde.

![image](https://user-images.githubusercontent.com/10848573/152837610-c15b53bb-51d4-48b6-b41f-d30edf93cbf0.png)

Ao tentar executar o programa me deparo com esse problema: 
```
Traceback (most recent call last):
  File "C:\Users\fenix\Documents\teste-Target\testeTarget\testetarget.py", line 36, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

Não encontrei no projeto nenhuma instrução de configuração,
como podemos prosseguir?

Abs.!!

**Comment by leticia-alves-ime** [comment]
Olá, boa tarde. Peço desculpas, pois realmente esqueci de deixar instruções
para este caso.
Para que o programa funcione é preciso instalar a biblioteca "numpy" do
python. Outra opção pode ser abrir no "Google Colab" e assim não precisaria
de instalação.
Acrescentei essas informações no projeto que está no github.

Muito obrigada por avisar.



Em seg., 7 de fev. de 2022 14:14, Lucas Vinicius ***@***.***>
escreveu:
